version: "3.9"

services:
  backend:
    build: ./backend
    container_name: log-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data   

  proxy:
    build: ./frontend
    container_name: log-proxy
    ports:
      - "8080:80"
    depends_on:
      - backend
