services:
  backend:
    build: ./backend
    container_name: log-backend
    expose:
      - "3001"

  frontend:
    build: ./frontend
    container_name: log-frontend
    expose:
      - "80"

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
